gcc update, think I can get started with the basic setup... hopefully...

diff --git a/gcc/PKGBUILD b/gcc/PKGBUILD
--- a/gcc/PKGBUILD
+++ b/gcc/PKGBUILD
@@ -4,7 +4,7 @@
 # toolchain build order: linux-api-headers->glibc->binutils->gcc->binutils->glibc
 # NOTE: libtool requires rebuilt with each new gcc version
 
-pkgname=('gcc' 'gcc-libs' 'gcc-fortran' 'gcc-objc' 'gcc-go')
+pkgname=('gcc' 'gcc-libs' 'gcc-fortran' 'gcc-objc' 'gcc-ada' 'gcc-go')
 pkgver=5.2.0
 _pkgver=5
 _islver=0.14.1
@@ -15,15 +15,15 @@ arch=('i686' 'x86_64')
 license=('GPL' 'LGPL' 'FDL' 'custom')
 url="http://gcc.gnu.org"
 makedepends=('binutils>=2.25' 'libmpc' 'gcc-ada' 'doxygen')
-#checkdepends=('dejagnu' 'inetutils')
+checkdepends=('dejagnu' 'inetutils')
 options=('!emptydirs')
 source=(ftp://gcc.gnu.org/pub/gcc/releases/gcc-${pkgver}/gcc-${pkgver}.tar.bz2
         #ftp://gcc.gnu.org/pub/gcc/snapshots/${_snapshot}/gcc-${_snapshot}.tar.bz2
         http://isl.gforge.inria.fr/isl-${_islver}.tar.bz2
         pr66035.patch)
-sha256sums=('5f835b04b5f7dd4f4d2dc96190ec1621b8d89f2dc6f638f9f8bc1b1014ba8cad'
-            '1f20561843eb9f6ae2076800bc45f3680ff7696520257cd5734ccfb843464cae'
-            '990d9a77419071b54cbd1ea3e59786359b030553118037fa8b1cedc5bb072122')
+md5sums=('a51bcfeb3da7dd4c623e27207ed43467'
+         '118d1a379abf7606a3334c98a8411c79'
+         '5b980076cd5fcbc3aff6014f306282dd')
 
 if [ -n "${_snapshot}" ]; then
   _basedir=gcc-${_snapshot}
@@ -64,42 +64,38 @@ build() {
   CFLAGS=${CFLAGS/-pipe/}
   CXXFLAGS=${CXXFLAGS/-pipe/}
 
-  ${srcdir}/${_basedir}/configure \
-    --prefix=/usr \
-    --libdir=/usr/lib \
-    --libexecdir=/usr/lib \
-    --mandir=/usr/share/man \
-    --infodir=/usr/share/info \
-    --with-bugurl=https://bugs.valhallalinux.com/ \
-    --with-pkgverson="Valhalla Linux"
-    --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ \
-    --enable-shared \
-    --disable-multilib \
-    --enable-threads=posix \
-    --enable-libmpx \
-    --with-system-zlib \
-    --with-isl \
-    --enable-__cxa_atexit \
-    --disable-libunwind-exceptions \
-    --enable-clocale=gnu \
-    --disable-libstdcxx-pch \
-    --disable-libssp \
-    --enable-gnu-unique-object \
-    --enable-linker-build-id \
-    --enable-lto \
-    --enable-plugin \
-    --enable-install-libiberty \
-    --with-linker-hash-style=gnu \
-    --enable-gnu-indirect-function \
-    --disable-multilib \
-    --disable-werror \
-    --enable-checking=release \
-    --with-default-libstdcxx-abi=gcc4-compatible
+  ${srcdir}/${_basedir}/configure --prefix=/usr \
+      --libdir=/usr/lib --libexecdir=/usr/lib \
+      --mandir=/usr/share/man --infodir=/usr/share/info \
+      --with-bugurl=https://bugs.valhallalinux.com/ \
+      --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ \
+      --enable-shared --enable-threads=posix --enable-libmpx \
+      --with-system-zlib --with-isl --enable-__cxa_atexit \
+      --disable-libunwind-exceptions --enable-clocale=gnu \
+      --disable-libstdcxx-pch --disable-libssp \
+      --enable-gnu-unique-object --enable-linker-build-id \
+      --enable-lto --enable-plugin --enable-install-libiberty \
+      --with-linker-hash-style=gnu --enable-gnu-indirect-function \
+      --disable-multilib --disable-werror \
+      --enable-checking=release \
+      --with-default-libstdcxx-abi=gcc4-compatible
 
   make
-  
+
   # make documentation
-  #make -C $CHOST/libstdc++-v3/doc doc-man-doxygen
+  make -C $CHOST/libstdc++-v3/doc doc-man-doxygen
+}
+
+check() {
+  cd ${srcdir}/gcc-build
+
+  # increase stack size to prevent test failures
+  # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=31827
+  ulimit -s 32768
+
+  # do not abort on error as some are "expected"
+  make -k check || true
+  ${srcdir}/${_basedir}/contrib/test_summary
 }
 
 package_gcc-libs()
@@ -111,10 +107,10 @@ package_gcc-libs()
   install=gcc-libs.install
 
   cd ${srcdir}/gcc-build
-  
+
   make -C $CHOST/libgcc DESTDIR=${pkgdir} install-shared
   rm ${pkgdir}/${_libdir}/libgcc_eh.a
-  
+
   for lib in libatomic \
              libcilkrts \
              libgfortran \
@@ -166,7 +162,7 @@ package_gcc()
 
   make -C $CHOST/libgcc DESTDIR=${pkgdir} install
   rm ${pkgdir}/usr/lib/libgcc_s.so*
-  
+
   make -C $CHOST/libstdc++-v3/src DESTDIR=${pkgdir} install
   make -C $CHOST/libstdc++-v3/include DESTDIR=${pkgdir} install
   make -C $CHOST/libstdc++-v3/libsupc++ DESTDIR=${pkgdir} install
@@ -180,7 +176,7 @@ package_gcc()
 
   make DESTDIR=${pkgdir} install-fixincludes
   make -C gcc DESTDIR=${pkgdir} install-mkheaders
-  
+
   make -C lto-plugin DESTDIR=${pkgdir} install
   install -dm755 ${pkgdir}/usr/lib/bfd-plugins/
   ln -s /usr/lib/gcc/$CHOST/${pkgver}/liblto_plugin.so \
@@ -281,6 +277,30 @@ package_gcc-objc()
   # Install Runtime Library Exception
   install -d ${pkgdir}/usr/share/licenses/gcc-objc/
   ln -s ../gcc-libs/RUNTIME.LIBRARY.EXCEPTION ${pkgdir}/usr/share/licenses/gcc-objc/
+}
+
+package_gcc-ada()
+{
+  pkgdesc="Ada front-end for GCC (GNAT)"
+  depends=("gcc=$pkgver-$pkgrel")
+  options=('staticlibs' '!emptydirs')
+  install=gcc-ada.install
+
+  cd ${srcdir}/gcc-build/gcc
+  make DESTDIR=$pkgdir ada.install-{common,info}
+  install -m755 gnat1 $pkgdir/${_libdir}
+
+  ln -s gcc ${pkgdir}/usr/bin/gnatgcc
+
+  # insist on dynamic linking, but keep static libraries because gnatmake complains
+  mv ${pkgdir}/${_libdir}/adalib/libgna{rl,t}-${_pkgver}.so ${pkgdir}/usr/lib
+  ln -s libgnarl-${_pkgver}.so ${pkgdir}/usr/lib/libgnarl.so
+  ln -s libgnat-${_pkgver}.so ${pkgdir}/usr/lib/libgnat.so
+  rm ${pkgdir}/${_libdir}/adalib/libgna{rl,t}.so
+
+  # Install Runtime Library Exception
+  install -d ${pkgdir}/usr/share/licenses/gcc-ada/
+  ln -s ../gcc-libs/RUNTIME.LIBRARY.EXCEPTION ${pkgdir}/usr/share/licenses/gcc-ada/
 }
 
 package_gcc-go()
